# Generated by Django 5.1.1 on 2024-09-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='\\static\\images\no_image.png', null=True, upload_to='recipe_images/'),
        ),
    ]
